# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Upsale Checkout"
client_id = "ef39723dff41e7bca3d1e83d52720f72"
application_url = "https://upsale-app--development.gadget.app/shopify/install"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://upsale-app--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "test-plus-zobek.myshopify.com"
